export interface Listing {
  id: string;
  category: "jobs" | "housing" | "discounts";
  title: string;
  company: string;
  location: string;
  salary?: string;
  price?: string;
  discount?: string;
  posted: string;
  tags: string[];
}

export const mockListings: Listing[] = [
  // Jobs
  {
    id: "j1",
    category: "jobs",
    title: "Barista — Part Time",
    company: "Gloria Jean's Coffees",
    location: "Sydney CBD",
    salary: "$28–32/hr",
    posted: "2 days ago",
    tags: ["Part-time", "Hospitality"],
  },
  {
    id: "j2",
    category: "jobs",
    title: "Retail Sales Associate",
    company: "JB Hi-Fi",
    location: "Melbourne, VIC",
    salary: "$27–30/hr",
    posted: "1 day ago",
    tags: ["Casual", "Retail"],
  },
  {
    id: "j3",
    category: "jobs",
    title: "Data Entry Clerk",
    company: "UniMelb Admin",
    location: "Parkville, VIC",
    salary: "$32/hr",
    posted: "5 hours ago",
    tags: ["On-campus", "Admin"],
  },
  {
    id: "j4",
    category: "jobs",
    title: "Kitchen Hand",
    company: "Guzman y Gomez",
    location: "Brisbane, QLD",
    salary: "$26–29/hr",
    posted: "3 days ago",
    tags: ["Evening", "Food"],
  },
  {
    id: "j5",
    category: "jobs",
    title: "Tutor — Mathematics",
    company: "University of Sydney",
    location: "Camperdown, NSW",
    salary: "$45/hr",
    posted: "1 week ago",
    tags: ["On-campus", "Education"],
  },
  {
    id: "j6",
    category: "jobs",
    title: "Warehouse Picker/Packer",
    company: "Amazon AU",
    location: "Western Sydney",
    salary: "$30–34/hr",
    posted: "4 days ago",
    tags: ["Casual", "Logistics"],
  },

  // Housing
  {
    id: "h1",
    category: "housing",
    title: "Shared Room in Surry Hills",
    company: "Private Listing",
    location: "Surry Hills, NSW",
    price: "$220/week",
    posted: "1 day ago",
    tags: ["Share house", "Inner city"],
  },
  {
    id: "h2",
    category: "housing",
    title: "Studio Apartment near UNSW",
    company: "Iglu Student Accommodation",
    location: "Kensington, NSW",
    price: "$380/week",
    posted: "3 days ago",
    tags: ["Studio", "Near campus"],
  },
  {
    id: "h3",
    category: "housing",
    title: "Room in 3BR Flat",
    company: "Private Listing",
    location: "Carlton, VIC",
    price: "$190/week",
    posted: "6 hours ago",
    tags: ["Share house", "Bills included"],
  },
  {
    id: "h4",
    category: "housing",
    title: "Student Lodge — Single Room",
    company: "Urbanest",
    location: "Adelaide, SA",
    price: "$280/week",
    posted: "2 days ago",
    tags: ["Student accom", "Furnished"],
  },
  {
    id: "h5",
    category: "housing",
    title: "Master Bedroom in Townhouse",
    company: "Private Listing",
    location: "South Brisbane, QLD",
    price: "$250/week",
    posted: "5 days ago",
    tags: ["Private room", "Ensuite"],
  },
  {
    id: "h6",
    category: "housing",
    title: "Shared Twin Room",
    company: "UniLodge",
    location: "Perth CBD, WA",
    price: "$165/week",
    posted: "1 week ago",
    tags: ["Twin share", "Budget"],
  },

  // Discounts
  {
    id: "d1",
    category: "discounts",
    title: "20% off UberEats Orders",
    company: "UberEats",
    location: "Australia-wide",
    discount: "20% off",
    posted: "Today",
    tags: ["Food", "Delivery"],
  },
  {
    id: "d2",
    category: "discounts",
    title: "Student Opal Card — Half Price",
    company: "Transport NSW",
    location: "Sydney, NSW",
    discount: "50% off",
    posted: "Ongoing",
    tags: ["Transport", "Government"],
  },
  {
    id: "d3",
    category: "discounts",
    title: "Apple Education Pricing",
    company: "Apple",
    location: "Australia-wide",
    discount: "Up to $400 off",
    posted: "Ongoing",
    tags: ["Tech", "Laptops"],
  },
  {
    id: "d4",
    category: "discounts",
    title: "Free Spotify Premium 3 Months",
    company: "Spotify",
    location: "Australia-wide",
    discount: "Free trial",
    posted: "2 days ago",
    tags: ["Entertainment", "Music"],
  },
  {
    id: "d5",
    category: "discounts",
    title: "10% off Woolworths Online",
    company: "Woolworths",
    location: "Australia-wide",
    discount: "10% off",
    posted: "3 days ago",
    tags: ["Groceries", "Online"],
  },
  {
    id: "d6",
    category: "discounts",
    title: "Student Gym Membership",
    company: "Fitness First",
    location: "All locations",
    discount: "$12.99/week",
    posted: "Ongoing",
    tags: ["Fitness", "Health"],
  },
];
